### ISSUE TITLE
WINDOWS 10:  errors with utils.generateTemporaryUsdFile when trying to open binary usd

### ISSUE THREAD

**Issue by bblackbourn** [dreamworksanimation/usdmanager#10]
As above.  Trying to "double click open" a binary usd file in usdmanager left hand panel produces error about unable to rename the temp file to usd,  It does create the usd as 0KB file but can't write to it.

Sorry for hacking away again Mark, but I noticed that, when using the same logic during the saveAs process, around line 992 in __init__.py, the temp file is closed **before** calling utils.usdcat

I moved the os.close in utils.py from the finally: (around line 154 ish) to line 150, just after the tempfile call and **before** the try: usdcat call.

Seems to work.

Being a noob, I don't really understand the finally: thing, so I just commented out the existing os.close and stuck in a print statement of the tmpFileName for now...so that it didn't give me a syntrax error.

Hope this is useful.

cheer mate
B

**Comment by mds-dwa** [comment]
Good catch! We'll get this patched up soon. Gotta love Windows vs. Unix differences...

**Note to self:** Switching from tempfile.mkstemp to tempfile.NamedTemporaryFile may be a better long-term plan.

**Comment by mds-dwa** [comment]
This should now be resolved in 0.6.0.

**Comment by bblackbourn** [comment]
Works for me.  Thanks Mark!
B


---- On Tue, 09 Jul 2019 19:13:53 +0000 Mark Sandell <notifications@github.com> wrote ----


This should now be resolved in 0.6.0.
