### ISSUE TITLE
WINDOWS 10: subProcess error when dynamically converting crate to ascii

### ISSUE THREAD

**Issue by bblackbourn** [dreamworksanimation/usdmanager#12]
Related to issue #8
When calling usdcat from utils.usdcat with a path that has a space in it, the call errors out with message about number of arguments (seems familiar...)

All works as expected if I wrap the construction of the cmd assembly (line 171ish of utils) in a similar method to fix for__init__ launchUsdView in issue #8 
ie
if os.name == 'nt':
    cmd = 'usdcat "{}" -o "{}"'.format(inputFile, outputFile)
else:
    cmd = "usdcat {} -o {}".format(inputFile, outputFile)

**Comment by mds-dwa** [comment]
I've updated the code based on your suggestion, and also preemptively updated the unzip logic for USDZ files, since it would likely suffer from the same issue. After a bit of internal testing, I should be able to get this out early next week.

**Comment by bblackbourn** [comment]
Nice one Mark. I'll keep an eye out.  Have a great weekend.

**Comment by mds-dwa** [comment]
This is now available in version 0.7.0. This release also has improvements for user preferences and some other minor bug/annoyance fixes. I hope it all works well for you! Please let me know if you run into any issues.
