### ISSUE TITLE
errors spawning processes in windows when path names contain spaces

### ISSUE THREAD

**Issue by bblackbourn** [dreamworksanimation/usdmanager#8]
When a usd file has spaces in it's absolute path (eg C:\temp\A Ball\Ball.usd) is open in usdmanager and then an attempt is made to use "open with usdview" in the commands menu a console error is produced about unrecognized arguments, as windows splits the path name at the spaces.

The issue seems to happen at around line 2471 of the __init__.py file in the launchUsdView proc.
getCurrentPath returns a string with spaces and when that is fed into the cmd, windows vomits it up.

A quick test of wrapping the result of getCurrentPath with double quotes results in windows happily opening the correct file in usdview.

**Comment by mds-dwa** [comment]
I've pushed the 0.5.0 release candidate to the dev branch with a fix for this, among other things. If you're able to confirm that it resolves the issue for you, it would be great to get that feedback before I make the official release. Thank you!

**Comment by bblackbourn** [comment]
Hi Mark,



I've given it a shot but now I'm getting a different error (sorry I can't copy/paste from my secure machine into this browser window).



so typing by hand and paraphrasing a little ...



Traceback 

 line 3130 of c:\Python27\lib\site-packages\usdmanager\__init__.py in launchProcess, p =subprocess.Popen(args, **kwargs)

line 710 of c:\Python27\lib\subprocess.py in __init__, errread, errwrite)

line 958 of c:\Python27\lib\subprocess.py in _execute_child, statupinfo)

WindowsError: [Error 2] The system cannot find the file specified





BTW I get the same error on my hacked version - if I try the "Open with text editor" menu entry



cheers

Brad


---- On Mon, 17 Jun 2019 16:38:12 +0000 Mark Sandell <notifications@github.com> wrote ----


I've pushed the 0.5.0 release candidate to the dev branch with a fix for this, among other things. If you're able to confirm that it resolves the issue for you, it would be great to get that feedback before I make the official release. Thank you!

**Comment by mds-dwa** [comment]
Thanks for the prompt feedback! While I did add the quotes for Windows paths, I also removed shell=True from that subprocess.Popen line, since it isn't really encouraged behavior from a python perspective. I wonder if we need that for Windows to actually keep the quotes. It looks like I'll have to get a Windows box setup for myself to test this out and dive deeper into the issue.

**Comment by bblackbourn** [comment]
No probs Mark.



FYI



0.5.0 release

the open with text editor doesn't work, it tries to open a file with called ".txt" in the root of c drive (no path or filename gets supplied to notepad.exe???  I've specified notepad in prefs.)

the path fed to usdview has single quotes outside the double quotes eg '"C:/temp/A Ball/Ball.usd"'.  If I try the same at the command line I get the same error "unable to open stage".  If I remove the single quotes it opens OK.



0.4.1 release

original code on line 3259 has shell=shell (doesn't open the text editor at all)

if I change to shell=True work perfectly, opens the usd file in notepad!  (this change doesn't seem to magically fix 0.5.0....)



cheers

B


---- On Mon, 17 Jun 2019 17:27:47 +0000 Mark Sandell <notifications@github.com> wrote ----


Thanks for the prompt feedback! While I did add the quotes for Windows paths, I also removed shell=True from that subprocess.Popen line, since it isn't really encouraged behavior from a python perspective. I wonder if we need that for Windows to actually keep the quotes. It looks like I'll have to get a Windows box setup for myself to test this out and dive deeper into the issue.

**Comment by mds-dwa** [comment]
Hi Brad, I have another commit that I'll push to that same pull request on the dev branch later today. I tested it last night on Windows and it worked for me, so I just need to double-check Linux again this morning. I think I was over complicating the solution before, so it's much simpler now with no OS-specific logic.

**Comment by bblackbourn** [comment]
Sounds promising!

End of my day here in UK, so I'll double check that tomorrow.  :-)

B

---- On Tue, 18 Jun 2019 16:20:01 +0000 Mark Sandell <notifications@github.com> wrote ----


Hi Brad, I have another commit that I'll push to that same pull request on the dev branch later today. I tested it last night on Windows and it worked for me, so I just need to double-check Linux again this morning. I think I was over complicating the solution before, so it's much simpler now with no OS-specific logic.

**Comment by mds-dwa** [comment]
Alright, the dev branch has been updated. Hopefully, this time does it!

For reference, I've tested this on CentOS 7 (Linux) and Windows 10, both with python 2.7.

**Comment by bblackbourn** [comment]
Oddly I'm still getting usdview issues.



Open with text editor works regardless of whether the path has spaces or not, but Open with usdview produces an error coming out of the subprocess.Popen at line 3132 that ends with a WindowsError:[Error 2] The system cannot find the file specified regardless of the file path.

So now it won't open any usd files in usdview, spaces or not.

Very strange.

---- On Tue, 18 Jun 2019 18:54:18 +0000 Mark Sandell <mailto:notifications@github.com> wrote ----


Alright, the dev branch has been updated. Hopefully, this time does it!

For reference, I've tested this on CentOS 7 (Linux) and Windows 10, both with python 2.7.

**Comment by mds-dwa** [comment]
Man, that's frustrating. A couple of questions to maybe make some progress on this:
* What version of Windows are you on?
* What python version are you using?
* Do you have a special config.json setting for where it should call usdview from?
* If you're running Command Prompt on Windows, is usdview executable as a normal command without having to do any special shell commands first? (Basically, I'm trying to check if usdmanager can find usdview from its run time environment.)

If you want to try a quick fix again, going back to our original quotes approach but for windows only AND usdview only (I was trying to find a global solution for all commands before, we could try replacing the entire launchUsdView method in usdmanager/__init__.py with this:
```
        app = self.app.appConfig.get("usdview", "usdview")
        path = self.currTab.getCurrentPath()
        if os.name == "nt":
            cmd = '{} "{}"'.format(app, path)
            self.launchProcess(cmd, shell=True)
        else:
            args = [app, path]
            self.launchProcess(args)
```

I'm really confused at the moment why this only effects usdview

**Comment by bblackbourn** [comment]
Yeah.  Annoying.



In case I didn't mention, my machine is running TPN secure so no external network connection, internet etc, so no pip installs, no github cloning, no outgoing file transport (only incoming via temp downloads folder that is not writable from local machine), no cut n paste into secure  RDS Chrome browser running on virtual machine where temp downloads folder is located etc etc  I also have no admin/root privileges so I can't run "normal" setup/install apps that try to write to system registry etc. 





So, to your questions:



Windows 10 Pro, version 1809, build 17763.557

Python 2.7.7 (so no setuptools,  this is why I needed to hack setup.py using distutils.setup and with a local find_packages module to do install)

usdmanager\config.json contains only "defaultPrograms" with empty value

If I open a command prompt and type: 
usdview C:\temp\Kitchen_set\Kitchen_set\assets\Ball\Ball.usd
the usd file opens fine.
If I close that and in the same shell type:
python C:\Python27\Scripts\usdmanager
usdmanager opens and behaves fine, I can open any usd files in the external text editor(including those with spaces in path), but it generates the previous mentioned error if I try to open any usd (including the same file as above) in usdview.

It's got me stumped.



---- On Wed, 19 Jun 2019 16:52:32 +0000 Mark Sandell <notifications@github.com> wrote ----


Man, that's frustrating. A couple of questions to maybe make some progress on this:

What version of Windows are you on?

What python version are you using?

Do you have a special config.json setting for where it should call usdview from?

If you're running Command Prompt on Windows, is usdview executable as a normal command without having to do any special shell commands first? (Basically, I'm trying to check if usdmanager can find usdview from its run time environment.)

**Comment by mds-dwa** [comment]
I pushed out v0.5.0 today with the double quotes and shell=True fix enabled for Windows only, since that worked successfully for you before. This is only implemented for usdview, since other apps (e.g. text editor) seem fine with the current methodology that worked cross-platform.

Thanks again for all your feedback testing this as we went back and forth. If you give me a thumbs up regarding this release next time you get a chance, I'll consider this resolved.

**Comment by bblackbourn** [comment]
All good Mark!

cheers

B


---- On Thu, 20 Jun 2019 21:37:05 +0000 Mark Sandell <notifications@github.com> wrote ----


I pushed out v0.5.0 today with the double quotes and shell=True fix enabled for Windows only, since that worked successfully for you before. This is only implemented for usdview, since other apps (e.g. text editor) seem fine with the current methodology that worked cross-platform.

Thanks again for all your feedback testing this as we went back and forth. If you give me a thumbs up regarding this release next time you get a chance, I'll consider this resolved.

**Comment by mds-dwa** [comment]
Hi Brad, if you're still around working in USD, I've got a new version in the dev branch that I'm hoping to get tested again, ideally removing shell=True again and changing how quotes are handled. If it fails again, I'll go back to the "nt" specific logic we had before.
